import { Project } from './types';

export const projects: Project[] = [
  // Major Projects
  {
    id: 'glass-frontier',
    name: 'The Glass Frontier',
    domain: 'glass-frontier.com',
    description: 'Solo GPT-guided narrative runs feed a persistent multiplayer world. Outcomes distill into shared lore, news, hubs, and future prompts. A post-apocalyptic sci-fi adventure with light fantasy and mystical elements.',
    status: 'development',
    category: 'major',
    tags: ['game', 'ai', 'narrative', 'multiplayer'],
    productUrl: 'https://glass-frontier.com',
    repoUrl: 'https://github.com/chris-arsenault/the-glass-frontier',
    lastUpdated: '2025-12-22',
    features: [
      'Chat-first UI with overlays for character sheet, map, inventory',
      'Quest log, faction standings, and news system',
      'Persistent multiplayer world',
    ],
  },
  {
    id: 'the-canonry',
    name: 'The Canonry',
    domain: 'the-canonry.com',
    description: 'A creative platform for building and sharing interactive experiences. Combines storytelling with game mechanics to create engaging content.',
    status: 'development',
    category: 'major',
    tags: ['platform', 'creative', 'interactive'],
    productUrl: 'https://the-canonry.com',
    repoUrl: 'https://github.com/chris-arsenault/the-canonry',
    lastUpdated: '2025-12-01',
  },
  {
    id: 'penguin-tales',
    name: 'Penguin Tales',
    domain: 'penguin-tales.com',
    description: 'Lore Weave - A procedural world generation framework for generating and visualizing rich, interconnected world histories through procedural templates, simulation systems, and interactive graph exploration.',
    status: 'development',
    category: 'major',
    tags: ['worldbuilding', 'procedural', 'simulation'],
    productUrl: 'https://penguin-tales.com',
    repoUrl: 'https://github.com/chris-arsenault/penguin-tales',
    lastUpdated: '2026-01-08',
    features: [
      'Growth templates and simulation systems',
      'JSON-based configuration',
      'Interactive graph exploration',
    ],
  },
  {
    id: 'tsonu-music',
    name: 'Tsonu Music',
    domain: 'music.tsonu.com',
    description: 'A personal music portfolio and streaming platform showcasing original compositions and audio experiments.',
    status: 'active',
    category: 'major',
    tags: ['music', 'portfolio', 'audio'],
    productUrl: 'https://music.tsonu.com',
    repoUrl: 'https://github.com/chris-arsenault/tsonu-music',
    lastUpdated: '2025-09-06',
  },
  // Minor Projects
  {
    id: 'hotsauce',
    name: 'Scorchbook',
    domain: 'hotsauce.tsonu.com',
    description: 'A hot sauce collection tracker and rating app. Snap photos, record tasting notes, and track your spicy adventures with AI-assisted cataloging.',
    status: 'beta',
    category: 'minor',
    tags: ['app', 'food', 'ai'],
    productUrl: 'https://hotsauce.tsonu.com',
    repoUrl: 'https://github.com/chris-arsenault/websites',
    lastUpdated: '2025-12-15',
    features: [
      'Photo and audio capture for tastings',
      'AI-powered sauce identification',
      'Heat and flavor ratings',
    ],
  },
  {
    id: 'ru-ai',
    name: 'RU-AI',
    domain: 'ru-ai.net',
    description: 'A playful human verification system that asks esoteric philosophical questions to determine if you are a robot. Features both Human Mode and Cat Mode.',
    status: 'active',
    category: 'minor',
    tags: ['experiment', 'ai', 'fun'],
    productUrl: 'https://ru-ai.net',
    repoUrl: 'https://github.com/chris-arsenault/websites',
    lastUpdated: '2025-12-20',
    features: [
      'Multiple challenge types',
      'Human Mode with philosophical questions',
      'Cat Mode for feline verification',
    ],
  },
  {
    id: 'slipstream',
    name: 'Slipstream',
    domain: 'github.com/chris-arsenault/slipstream',
    description: 'A lightweight, high-performance clipboard manager for Windows that gives you superpowers without getting in your way.',
    status: 'active',
    category: 'minor',
    tags: ['utility', 'windows', 'productivity'],
    productUrl: 'https://github.com/chris-arsenault/slipstream/releases/latest',
    repoUrl: 'https://github.com/chris-arsenault/slipstream',
    lastUpdated: '2025-12-17',
    features: [
      'Lightweight and high-performance',
      'Installer or portable exe',
      'Quick access to clipboard history',
    ],
  },
];
