import { Project } from './types';

export const projects: Project[] = [
  // Major Projects
  {
    id: 'glass-frontier',
    name: 'The Glass Frontier',
    domain: 'glass-frontier.com',
    description: 'Solo GPT-guided narrative runs feed a persistent multiplayer world. Outcomes distill into shared lore, news, hubs, and future prompts. A post-apocalyptic sci-fi adventure with light fantasy and mystical elements.',
    status: 'development',
    category: 'major',
    tags: ['game', 'ai', 'narrative', 'multiplayer'],
    productUrl: 'https://glass-frontier.com',
    repoUrl: 'https://github.com/chris-arsenault/the-glass-frontier',
    lastUpdated: '2025-12-22',
    features: [
      'Chat-first UI with overlays for character sheet, map, inventory',
      'Quest log, faction standings, and news system',
      'Persistent multiplayer world',
    ],
  },
  {
    id: 'the-canonry',
    name: 'The Canonry',
    domain: 'the-canonry.com',
    description: 'Lore Weave - A domain-agnostic procedural history generation framework for creating rich, interconnected world histories through procedural templates, simulation systems, and interactive graph exploration.',
    status: 'development',
    category: 'major',
    tags: ['worldbuilding', 'procedural', 'simulation', 'framework'],
    productUrl: 'https://the-canonry.com',
    repoUrl: 'https://github.com/chris-arsenault/the-canonry',
    lastUpdated: '2026-01-08',
    features: [
      'Domain-agnostic history generation',
      'Growth templates and simulation systems',
      'JSON-based configuration',
      'Interactive graph exploration',
    ],
  },
  {
    id: 'the-ice-remembers',
    name: 'The Ice Remembers',
    domain: 'theiceremembers.com',
    description: 'A fully illuminated penguin history built on The Canonry framework. An immersive showcase of procedural worldbuilding featuring the complete chronicles of penguin civilization.',
    status: 'development',
    category: 'major',
    tags: ['worldbuilding', 'penguins', 'lore', 'showcase'],
    productUrl: 'https://theiceremembers.com',
    repoUrl: 'https://github.com/chris-arsenault/the-ice-remembers',
    lastUpdated: '2026-01-08',
    features: [
      'Over 200 AI-generated penguin illustrations',
      '30+ in-universe stories and documents',
      'Complete penguin civilization timeline',
    ],
  },
  {
    id: 'hot-mic',
    name: 'HotMic',
    domain: 'github.com/chris-arsenault/hot-mic',
    description: 'A lightweight Windows audio router for dual microphones with professional DSP, AI noise reduction, and VST plugin hosting. Built for podcasters, streamers, and audio professionals who need clean routing without bloat.',
    status: 'development',
    category: 'major',
    tags: ['audio', 'dsp', 'windows', 'ai'],
    productUrl: 'https://github.com/chris-arsenault/hot-mic/releases/latest',
    repoUrl: 'https://github.com/chris-arsenault/hot-mic',
    lastUpdated: '2026-02-10',
    features: [
      'Dual-mic WASAPI capture with low-latency routing',
      'AI noise reduction with RNNoise and voice activity detection',
      'VST2/VST3 plugin hosting with MIDI Learn',
    ],
  },
  {
    id: 'tsonu-music',
    name: 'Tsonu Music',
    domain: 'music.tsonu.com',
    description: 'A personal music portfolio and streaming platform showcasing original compositions and audio experiments.',
    status: 'active',
    category: 'major',
    tags: ['music', 'portfolio', 'audio'],
    productUrl: 'https://music.tsonu.com',
    repoUrl: 'https://github.com/chris-arsenault/tsonu-music',
    lastUpdated: '2025-09-06',
  },
  // Minor Projects
  {
    id: 'scorchbook',
    name: 'Scorchbook',
    domain: 'scorchbook.tsonu.com',
    description: 'A hot sauce collection tracker and rating app. Snap photos, record tasting notes, and track your spicy adventures with AI-assisted cataloging.',
    status: 'active',
    category: 'minor',
    tags: ['app', 'food', 'ai'],
    productUrl: 'https://scorchbook.tsonu.com',
    repoUrl: 'https://github.com/chris-arsenault/websites/tree/main/apps/scorchbook',
    lastUpdated: '2026-01-09',
    features: [
      'Photo and audio capture for tastings',
      'AI-powered sauce identification',
      'Heat and flavor ratings',
    ],
  },
  {
    id: 'ru-ai',
    name: 'RU-AI',
    domain: 'ru-ai.net',
    description: 'A playful human verification system that asks esoteric philosophical questions to determine if you are a robot. Features both Human Mode and Cat Mode.',
    status: 'active',
    category: 'minor',
    tags: ['experiment', 'ai', 'fun'],
    productUrl: 'https://ru-ai.net',
    repoUrl: 'https://github.com/chris-arsenault/websites',
    lastUpdated: '2025-12-20',
    features: [
      'Multiple challenge types',
      'Human Mode with philosophical questions',
      'Cat Mode for feline verification',
    ],
  },
  {
    id: 'stack-atlas',
    name: 'Stack Atlas',
    domain: 'stack-atlas.ahara.io',
    description: 'A technology stack standardization tool. Browse a canonical inventory of technologies, tools, and patterns, select what you use, and export clean stack definitions.',
    status: 'active',
    category: 'minor',
    tags: ['tool', 'devops', 'standards'],
    productUrl: 'https://stack-atlas.ahara.io',
    repoUrl: 'https://github.com/chris-arsenault/websites/tree/main/apps/stack-atlas',
    lastUpdated: '2026-02-10',
    features: [
      'Browse 14 technology categories',
      'Filter by type, tags, and search',
      'Export stack definitions as Markdown or JSON',
    ],
  },
  {
    id: 'slipstream',
    name: 'Slipstream',
    domain: 'github.com/chris-arsenault/slipstream',
    description: 'A lightweight, high-performance clipboard manager for Windows that gives you superpowers without getting in your way.',
    status: 'active',
    category: 'minor',
    tags: ['utility', 'windows', 'productivity'],
    productUrl: 'https://github.com/chris-arsenault/slipstream/releases/latest',
    repoUrl: 'https://github.com/chris-arsenault/slipstream',
    lastUpdated: '2025-12-17',
    features: [
      'Lightweight and high-performance',
      'MIDI controller support',
      'Onscreen slot GUI',
    ],
  },
];
